# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: deploy-products

on:
  push:
    branches:
      - deploy
    paths:
      - "frontend/products/**"

defaults:
  run:
    working-directory: frontend/products

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      # - uses: shinyinc/action-aws-cli@v1.2
      # - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ""
