# 7.0.5-alpine, 7.0-alpine, 7-alpine, alpine, 7.0.5-alpine3.16, 7.0-alpine3.16, 7-alpine3.16, alpine3.16
FROM redis:7.0-alpine
COPY redis-v7_0-6391.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
