'use strict';
import { cpus } from 'os';
import { Worker } from 'worker_threads';

const VERBOSE = false;
const CORES = cpus().length;
type Strategies = 'roundrobin' | 'random' | 'leastbusy';
const STRATEGIES = new Set<Strategies>(['roundrobin', 'random', 'leastbusy']);
export class RpcWorkerPool {
  private size: number;
  private strategy: Strategies;
  private versosity: boolean;
  private rr_index: number;
  private next_job_id: number;
  private workers: { worker: Worker; in_flight_commands: Map<number, any> }[];
  constructor(
    path: string,
    size: number = 0,
    strategy: Strategies = 'leastbusy',
    versosity = VERBOSE
  ) {
    this.size = size < 0 ? Math.max(CORES + size, 1) : size || CORES;
    this.strategy = STRATEGIES.has(strategy) ? strategy : 'leastbusy';
    this.versosity = versosity;

    this.rr_index = -1;
    this.next_job_id = 0;
    this.workers = [];
    for (let worker_id = 0; worker_id < this.size; worker_id++) {
      const worker = new Worker(path);
      this.workers.push({ worker, in_flight_commands: new Map() });
      worker.on('message', msg => {
        this.onMessageHandler(msg, worker_id);
      });
    }
  }
  // ++ --------------------------------------------------------------
  onMessageHandler(msg: any, worker_id: number) {
    const worker = this.workers[worker_id];

    const { result, error, job_id } = msg;

    // resolve: (value: any) => void, reject: (reason?: any) =>
    const { resolve, reject } = worker.in_flight_commands.get(job_id);
    worker.in_flight_commands.delete(job_id);

    if (error) reject(error);
    else resolve(result);
  }
  // ++ --------------------------------------------------------------

  async exec(method_name: string, message_id: number, ...args: string[]) {
    const job_id = this.next_job_id++;

    // The message_id is provided for feedback purpose only.
    const worker = this.getWorker(message_id);

    const promise = new Promise((resolve, reject) => {
      worker.in_flight_commands.set(job_id, { resolve, reject });
    });
    worker.worker.postMessage({ method_name, params: args, job_id });

    return promise;
  }
  // ++ --------------------------------------------------------------
  getWorker(message_id = -1) {
    let worker_id: number = 0;
    switch (this.strategy) {
      case 'random':
        worker_id = Math.floor(Math.random() * this.size);
        break;
      case 'roundrobin':
        this.rr_index++;
        if (this.rr_index >= this.size) this.rr_index = 0;
        worker_id = this.rr_index;
        break;
      case 'leastbusy':
      default:
        let min = Infinity;
        for (let i = 0; i < this.size; i++) {
          let worker = this.workers[i];
          if (worker.in_flight_commands.size < min) {
            min = worker.in_flight_commands.size;
            worker_id = 0;
          }
        }
    }

    this.versosity &&
      console.log(`'Worker: ${worker_id + 1} Message id: ${message_id || 0}\n`);

    return this.workers[worker_id];
  }
}

export default RpcWorkerPool;

/**
 * The size of the worker pool
 * @member @type {number}
 */
/**
 * The strategie to determine the worker to be to execude the next
 * command.
 * @member @type {Strategies}
 */
/**
 * Determines the verbosity of certain informations to log.
 * @member @type {boolean}
 */
/**
 * @param {string} method_name - The name of the method listed in
 * the available commands.
 * @param {number} message_id - The sequential number generated by
 * the server, identifies which message will be linked with the
 * curent job being executed. (For feedback purpose only).
 */
/* **************************************************************** */
/*                                                                  */
/*  MIT LICENSE                                                     */
/*                                                                  */
/*  Copyright © 2021-2022 Benjamin Vincent Kasapoglu (Luxcium)      */
/*                                                                  */
/*  NOTICE:                                                         */
/*  O’Reilly Online Learning                                        */
/*                                                                  */
/*  Title: “Multithreaded JavaScript”                               */
/*  Author: “by Thomas Hunter II and Bryan English”                 */
/*  Publisher: “O’Reilly”                                           */
/*  Copyright: “© 2022 Thomas Hunter II and Bryan English”          */
/*  ISBN: “978-1-098-10443-6.”                                      */
/*                                                                  */
/*  Using Code Examples                                             */
/*  Supplemental material (code examples, exercises, etc.)          */
/*  is available for download at                                    */
/*  https://github.com/MultithreadedJSBook/code-samples.            */
/*                                                                  */
/*  In general, if example code is offered with this book, you may  */
/*  use it in your programs and documentation. You do not need to   */
/*  contact us for permission unless you’re reproducing a           */
/*  significant portion of the code. For example, writing a         */
/*  program that uses several chunks of code from this book does    */
/*  not require permission. Selling or distributing examples from   */
/*  O’Reilly books does require permission. Answering a question by */
/*  citing this book and quoting example code does not require      */
/*  permission. Incorporating a significant amount of example code  */
/*  from this book into your product’s documentation does require   */
/*  permission.                                                     */
/*                                                                  */
/*  If you feel your use of code examples falls outside fair use or */
/*  the permission given above, feel free to contact us at          */
/*  permissions@oreilly.com.                                        */
/*                                                                  */
/* **************************************************************** */
