#!/usr/bin/bash
# Create an array of the directories to iterate over
directories=(backend common docker docs examples frontend library private scripts services static)

# Iterate over the directories array
for directory in "${directories[@]}"; do
  # Check if the directory exists
  if [ -d "$directory" ]; then
    # Create an empty README.md file in the directory
    echo "† Scientia es lux principium✨ ™" >>"$directory/README.md"
  fi
done
# Credit: This script was generated by ChatGPT (https://openai.com/)
